spring:
  application:
    name: ap
  datasource:
    url: jdbc:oracle:thin:@//34.50.37.11:1522/XEPDB1
    username: BNK
    password: abc1234!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: AP_HikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 15000
      auto-commit: true

  # 웹 서버 비활성화 (소켓 서버만 사용)
  main:
    web-application-type: none

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true